version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: psswd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  strapi:
    image: strapi/strapi
    container_name: strapi
    restart: always
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: my_database
      DATABASE_USERNAME: my_user
      DATABASE_PASSWORD: psswd
      DATABASE_SSL: 'false'
    ports:
      - "1337:1337"
    depends_on:
      - mysql
    volumes:
      - ./strapi-app:/srv/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - strapi

volumes:
  mysql-data:
